version: '3.8'

services:
  web:
    build: ./app    #указываем где лежит докер-файл
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://username:password@postgres:5432/testdb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - postgres_data1:/var/lib/postgresql/data

volumes:
  postgres_data1: